### PR TITLE
issue #8 aligin interface with can-define-validate-validate

### PR DESCRIPTION
**Pull request by frank-dspeed**
https://github.com/canjs/can-define-backup/issues/8

### CODE REVIEW

**Comment by frank-dspeed** [comment]
@phillipskevin please review documentation is also upgraded all tests passing

**Review by phillipskevin — CHANGES_REQUESTED** [review]
@frank-dspeed this is great. A couple things:

1. Can you rebase with master?

2. Can you change the spaces back to tabs? If you install editorconfig for your editor, it should handle it automatically.

**Comment by phillipskevin** [comment]
Also, sorry it took so long to review. If you can make those couple changes we can release this asap.

**Comment by phillipskevin** [comment]
Taking care of this in https://github.com/canjs/can-define-backup/pull/12. Thanks @frank-dspeed.

**Pull request closed without merging**
